version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout
      - run:
          name: Instalar Railway CLI
          command: npm install -g @railway/cli
      - run:
          name: Verificar versión Railway
          command: railway --version
      - run:
          name: Autenticarse en Railway
          command: |
            echo "$RAILWAY_TOKEN" | railway login --no-interactive
      - run:
          name: Desplegar aplicación
          command: railway up --service=empty-project-production-282d --detach

workflows:
  deploy_on_main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main

